header/urls.py
from django.urls import path

from .import views

app_name="header"
urlpatterns = [
    path('', views.ListView.as_view(), name="list"),
    path('create', views.HeaderCreateView.as_view(), name="create"),
    path('detail/<int:pk>', views.HeaderUpdateView.as_view(), name="update"),
    path('get-detail-list/<int:headerId>', views.getDetailList, name="getDetailList"),
    path('update-comment', views.updateComment, name="updateComment"),
]

manageType/urls.py
from django.urls import path

from .import views
from .import views

app_name="manageType"
urlpatterns = [
    path('', views.ListView.as_view(), name="list"),
    path('create/', views.TypeCreateView.as_view(), name="create"),
    path('detail/<int:pk>', views.TypeUpdateView.as_view(), name="update"),
    path('delete/<int:pk>', views.TypeDeleteView.as_view(), name="delete"),
]

ticket/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('header.urls')),
    path('config/', include('manageType.urls')),
    path('admin/', admin.site.urls),
]

header/models.py
from django.db import models
from manageType.models import Type
from django.utils import timezone

# Create your models here.
class Header(models.Model):
    """課題ヘッダー"""
    TYPE_CLS_CHOICES = [
        (1, "周知"),
        (2, "検討"),
        (3, "作業"),
    ]
    STATUS_CHOICES = [
        (1, "未着手"),
        (2, "着手中"),
        (3, "完了"),
    ]
    type_cls = models.ForeignKey(Type, models.SET_NULL, null=True)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.CharField(verbose_name='内容', max_length=1000, blank=True, null=True)
    limit_date = models.DateField(verbose_name='期限', blank=True, null=True)
    status = models.IntegerField(verbose_name="ステータス", choices = STATUS_CHOICES, default = 1)

    class Meta:
        verbose_name_plural = 'Header'
        verbose_name = '課題ヘッダー'

    def __str__(self):
        return self.title


class Detail(models.Model):
    """課題明細"""
    header_id = models.ForeignKey(Header, on_delete=models.CASCADE, verbose_name='ヘッダーID')
    content = models.CharField(verbose_name='内容', max_length=1000, blank=True, null=True)
    create_at = models.DateField(verbose_name='作成日', default=timezone.now)

    class Meta:
        verbose_name_plural = 'Detail'
        verbose_name = '課題明細'

    def __str__(self):
        return str(self.header_id_id) + '　' + self.content[:20]

manageType/models.py
from django.db import models
from colorfield.fields import ColorField

# Create your models here.
class Type(models.Model):
    class Meta:
        verbose_name='種別'

    sortCd = models.IntegerField(verbose_name='順番', unique=True)
    name = models.CharField(verbose_name='名前', max_length=10)
    color = ColorField(verbose_name='表示色', default='#FF0000')

header/views.py
from django.views import generic
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.core import serializers
from django.http import HttpResponse
from django.http import QueryDict
from .form import HeaderForm, HeaderUpdateForm
from .models import Header, Detail
from manageType.models import Type
import json
from django.utils import timezone

class ListView(generic.ListView):
    template_name = "header/list.html"
    model = Header
    paginate_by = 5

    def get_queryset(self):
        headers = Header.objects.order_by("type_cls__sortCd")
        return headers

class HeaderCreateView(CreateView):
    template_name = "header/create.html"
    model = Header
    form_class = HeaderForm

    success_url = reverse_lazy('header:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type_list'] = Type.objects.all().order_by('sortCd')
        return context

    def form_valid(self, form):
        messages.success(self.request, '追加しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '追加に失敗しました。')
        return super().form_invalid(form)

class HeaderUpdateView(generic.edit.UpdateView):
    template_name = "header/update.html"
    form_class = HeaderUpdateForm
    model = Header

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        #model = Header.objects.get(pk=context['pk'])

        return context


    def form_valid(self, form):
        messages.success(self.request, '更新しました。')

        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '更新に失敗しました。')
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse('header:update', kwargs = {'pk': self.kwargs['pk']})

def getDetailList(request, headerId):

    details = Detail.objects.filter(header_id = headerId)
    jsonDetails = serializers.serialize('json', details)

    return HttpResponse(jsonDetails, content_type="text/json-comment-filtered")

def updateComment(request):

    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)
    addContent = body['addContent']
    headerId = body['headerId']
    status = body['status']

    header = Header.objects.get(pk = headerId)
    header.status = status
    header.save()

    detail = Detail(header_id = header, content = addContent, create_at = timezone.now())
    detail.save()

    details = Detail.objects.filter(header_id=headerId)
    jsonDetails = serializers.serialize('json', details)

    return HttpResponse(jsonDetails, content_type="text/json-comment-filtered")
# 忘備
# 参考リスト
# https://docs.djangoproject.com/ja/3.2/ref/csrf/
# https://qiita.com/kakimochi/items/4e95c9e4d1e4b00ec05a

manageType/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages

from .models import Type
from .form import TypeForm


# Create your views here.
class ListView(generic.ListView):
    template_name = "manageType/list.html"
    model = Type

    def get_queryset(self):
        types = Type.objects.order_by('sortCd')
        return types

class TypeCreateView(generic.edit.CreateView):
    template_name = "manageType/create.html"
    model = Type
    form_class = TypeForm

    success_url = reverse_lazy('manageType:list')

    def form_valid(self, form):
        messages.success(self.request, '追加しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '追加に失敗しました。')
        return super().form_invalid(form)


class TypeUpdateView(generic.edit.UpdateView):
    template_name = "manageType/update.html"
    model = Type
    form_class = TypeForm

    success_url = reverse_lazy('manageType:list')

    def form_valid(self, form):
        messages.success(self.request, '更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        for field in form:
            for error in field.errors:
                messages.error(self.request, error)

        return super().form_invalid(form)



class TypeDeleteView(generic.edit.DeleteView):
    model = Type
    success_url = reverse_lazy('manageType:list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, '削除しました。')
        return super().delete(request, *args, **kwargs)

header/templates/header/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- bootstrap css-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="{% static 'font/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="container">
    <div class="alert alert-secondary side-menu-close" id="side-menu">
        <div id="menu-btn" class="text-right"><i class="bi bi-list" style="font-size: 28px"></i></div>
        <div id="menu-list">
            <div class="menu-item menu-item-close"><a href="{% url 'header:list' %}"><i class="bi bi-card-list menu-icon" style="font-size: 28px"></i><span class="menu-text menu-text-close">課題一覧</span></a>
            </div>
            <div class="menu-item menu-item-close"><a href="{% url 'manageType:list' %}"><i class="bi bi-gear menu-icon" style="font-size: 28px"></i><span class="menu-text menu-text-close">種別一覧</span></a>
            </div>
            <!--<div class="menu-item menu-item-close"><a href="#"><i class="bi bi-question menu-icon" style="font-size: 28px"></i><span class="menu-text menu-text-close">about</span></a>
            </div>-->
        </div>
    </div>
    <div id="content">
        {% if messages %}
            <div class="p-3">
            <ul class="col-lg-11 ml-auto mr-auto">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
                        {{message}}
                    </li>
                {% endfor %}
            </ul>
            </div>
        {% endif %}
        {% block content-area %}{% endblock %}
    </div>
</div>


<!-- bootstrap js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
<script src="{% static 'js/base.js' %}"></script>
{{ form.media }}

</body>
</html>

header/templates/header/create.html
{% extends 'header/base.html' %}
{% load static %}

{% block title %}課題作成{% endblock %}

{% block content-area %}
<h1 class="p-3">課題作成</h1>
<div class="px-5">
    <form method="post" class="container">
        {% csrf_token %}
        <!-- まとめて       {{ form.as_p }}-->
        <!--手動でhtmlを作ろうとするとこんな感じ
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
            &lt;!&ndash;            <input type="text" class="form-control" id="{{ form.title.id_for_label }}" name="{{ form.title.html_name }}">&ndash;&gt;
            {{ form.title }}
        </div>
        {% for v in form.type_cls.field.choices %}
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{ form.type_cls.html_name }}" id="exampleRadios1" value="{{ v.0 }}"
                   >
            <label class="form-check-label" for="exampleRadios1">
                {{ v.1 }}
            </label>
        </div>
        {% endfor %}-->
        {% for field in form %}
        <div class="form-group row">
            <label class="col-lg-2 col-form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
            <div class="col-lg-8">
                {{ field }}
            </div>
        </div>


        {% endfor %}


        <a type="button" class="btn btn-outline-dark" href="{% url 'header:list' %}"><i class="bi bi-arrow-left mr-1"
                                                                                        style="font-size:20px"></i>戻る</a>
        <button type="submit" class="btn btn-outline-success">
            <i class="bi bi-plus mr-1" style="font-size:20px"></i>登録
        </button>

    </form>

</div>

<script type="text/javascript">

    typeList = Array(0)
    {% for item in type_list %}
    var type = {id:{{ item.id }} , color:"{{ item.color }}" };
    typeList.push(type);
    {% endfor %}

    document.addEventListener('DOMContentLoaded', function() {


        // 種別のイベント
        document.getElementById('{{ form.type_cls.id_for_label }}').addEventListener('change',
            function() {
                var type = typeList.find(x => x.id == this.value);
                if (type) {
                    this.style.background = type.color
                } else {
                    this.style.background = "#FFFFFF"
                }

            }, false);
  // タグ内にjavascriptコードを直接記述します。
  console.log("JavaScriptを実行しています");
  {% for v in type_list %}
    console.log("{{v.name}}"+{{v.id}});
  {% endfor %}
  },false);
</script>
<style>
#{{ form.type_cls.id_for_label }} option:first-child {
        background: #FFFFFF
    }
{% for item in type_list %}
    #{{ form.type_cls.id_for_label }} option:nth-child({{forloop.counter|add:"1" }}) {
        background:{{ item.color }}
    }
{% endfor %}
</style>
{% endblock %}

header/templates/header/list.html
{% extends 'header/base.html' %}
{% load static %}

{% block title %}課題一覧{% endblock %}

{% block content-area %}
<h1 class="p-3">課題一覧</h1>
<div class="px-5">
    <!-- ページネーション処理 -->
    {% if is_paginated %}
        <ul class="pagination">
            <!-- 前ページへのリンク -->
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            <!-- ページ数表示 -->
            {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
            {% endfor %}

            <!-- 次ページへのリンク -->
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
    <div class="text-right mb-1">
        <a type="button" class="btn btn-outline-dark" href="{% url 'header:create' %}"><i class="bi bi-plus mr-1" style="font-size:20px"></i>課題を追加する</a>
    </div>
    <table class="table table-hover">
        <colgroup>
            <col style="width: 5%">
            <col style="width: 15%">
            <col style="width: 20%">
            <col style="width: 50%">
            <col style="width: 10%">
        </colgroup>
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">ステータス</th>
            <th scope="col">種別</th>
            <th scope="col">タイトル</th>
            <th scope="col">期限</th>
        </tr>
        </thead>
        <tbody>
        {% for item in header_list %}
        <tr onclick="window.location.href = '{% url 'header:update' item.pk %}'">
            <th scope="row">{{forloop.counter}}</th>
            <td>{{item.get_status_display }}</td>
            <td><div style="background: {{item.type_cls.color}}; padding:3px; 10px;">{{item.type_cls.name }}</div></td>
            <td>{{item.title}}</td>
            <td>{{item.limit_date|default_if_none:""}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

header/templates/header/update.html
{% extends 'header/base.html' %}
{% load static %}

{% block title %}課題更新{% endblock %}

{% block content-area %}
<h1 class="p-3">課題更新</h1>
<div class="px-5" id="app">
    <div class="container">
        <button type="button" class="btn btn-outline-success" v-on:click="switchMode">
            <i class="bi bi-pencil-square mr-1" style="font-size:20px"></i>編集
        </button>
        <div v-if="mode">
            <div class="mt-3">
                <div class="mb-2">期限：{{ header.limit_date }}</div>
                <span style="background: {{header.type_cls.color}}; padding:3px; 10px; margin-right:1rem">{{ header.type_cls.name }}</span>
                <span>{{ header.title }}</span>



                <div class="details-area">
                    <h5>コメント([[ details.length ]])</h5>
                    <div v-for="item in details" class="detail">
                        <div class="detail-date">[[ item.fields.create_at ]]</div>
                        <div class="detail-content">[[ item.fields.content ]]</div>
                    </div>
                </div>

            </div>

            <div v-bind:class="{'detail-add-open': dispAddFlg, 'detail-add-close': !dispAddFlg}" id="detail-add-input">
                <button type="button" class="btn btn-outline-dark" v-on:click="switchAdd">
                    <i class="bi bi-plus mr-1" style="font-size:20px"></i>コメント追加
                </button>
                <div class="row">
                    <div class="col-md-10">
                        <textarea class="comment" v-model="addContent">
                        </textarea>
                    </div>
                    <div class="col-md-2">
                        <div class="pr-3 mb-3">
                            <select name="status" id="id_status" class="form-control" v-model="status">
                            {% for item in header.STATUS_CHOICES %}
                                <option value="{{ item.0}}">{{ item.1 }} </option>
                            {% endfor %}
                        </select>
                        </div>
                        <button type="submit" class="btn btn-outline-info" v-on:click="updateComment">
                        <i class="bi bi-plus mr-1" style="font-size:20px"></i>更新
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <form method="post" v-if="!mode">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row">
                <label class="col-lg-2 col-form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col-lg-8">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <a type="button" class="btn btn-outline-dark" href="{% url 'header:list' %}"><i
                    class="bi bi-arrow-left mr-1"
                    style="font-size:20px"></i>戻る</a>
            <button type="submit" class="btn btn-outline-success">
                <i class="bi bi-plus mr-1" style="font-size:20px"></i>更新
            </button>
        </form>

    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<script>
  var vm = new Vue({
  delimiters: ['[[', ']]'],
  el: '#app',
  data: {
    headerId: {{ header.pk }},
    status: {{ header.status }},
    details: [],
    addContent: '',
    mode: true,
    dispAddFlg: false,
  },
  methods: {
    switchMode: function() {
        this.mode = !this.mode
    },
    switchAdd: function() {
        this.dispAddFlg = !this.dispAddFlg
    },
    updateComment: function() {
        axios.defaults.xsrfCookieName = 'csrftoken';
        axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";

        axios
            .post("{% url 'header:updateComment' %}",
                {headerId: this.headerId, addContent: this.addContent, status: this.status})
            .then(res => {
                this.details = res.data;
                this.addContent;
            })
    }
  },
  created: function() {

/* XMLHttpRequestを使った場合の実装
				var xhr = new XMLHttpRequest();
				xhr.onreadystatechange = function(){
					if(xhr.readyState === 4) {
						if (xhr.status === 200) {
						    console.log('OK')
						}
					} else {

					}
				}.bind(this);
				xhr.open('GET', "{% url 'header:getDetailList' header.pk %}", true);
				xhr.send(null);
*/

                axios
                    .get("{% url 'header:getDetailList' header.pk %}")
                    .then(res => {
                        console.log(res.data);
                        this.details = res.data
                    })

			},
})

</script>
{% endblock %}

header/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}課題一覧{% endblock %}

{% block content-area %}
<h1 class="p-3">課題一覧</h1>
<div class="px-5">
    <button type="button" class="btn btn-outline-dark"><i class="bi bi-plus mr-1" style="font-size:20px"></i>追加</button>
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">ステータス</th>
            <th scope="col">種別</th>
            <th scope="col">タイトル</th>
            <th scope="col">期限</th>
        </tr>
        </thead>
        <tbody>
        {% for item in header_list %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{item.get_status_display }}</td>
            <td>{{item.get_type_cls_display }}</td>
            <td>{{item.title}}</td>
            <td>{{item.limit_date}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

manageType/templates/manageType/create.html
{% extends 'header/base.html' %}
{% load static %}

{% block title %}課題作成{% endblock %}

{% block content-area %}
<h1 class="p-3">課題作成</h1>
<div class="px-5">
    <form method="post" class="container">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group row">
            <label class="col-lg-2 col-form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
            <div class="col-lg-2">
                {{ field }}
            </div>
        </div>


        {% endfor %}


        <a type="button" class="btn btn-outline-dark" href="{% url 'manageType:list' %}"><i class="bi bi-arrow-left mr-1"
                                                                                        style="font-size:20px"></i>戻る</a>
        <button type="submit" class="btn btn-outline-success">
            <i class="bi bi-plus mr-1" style="font-size:20px"></i>登録
        </button>

    </form>

</div>
{% endblock %}

manageType/templates/manageType/list.html
{% extends 'header/base.html' %}
{% load static %}

{% block title %}種別一覧{% endblock %}

{% block content-area %}
<h1 class="p-3">種別一覧</h1>
<div class="px-5">
    <div class="text-right mb-1">
        <a type="button" class="btn btn-outline-dark" href="{% url 'manageType:create' %}"><i class="bi bi-plus mr-1" style="font-size:20px"></i>種別を追加する</a>
    </div>
    <table class="table table-hover">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">表示順</th>
            <th scope="col">名前</th>
        </tr>
        </thead>
        <tbody>
        {% for item in type_list %}
        <tr onclick="window.location.href = '{% url 'manageType:update' item.pk %}'">
            <th scope="row">{{forloop.counter}}</th>
            <td>{{item.sortCd }}</td>
            <td><div style="background: {{item.color}}; padding:3px; 10px;">{{item.name }}</div></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

manageType/templates/manageType/update.html
{% extends 'header/base.html' %}
{% load static %}

{% block title %}種別更新{% endblock %}

{% block content-area %}
<h1 class="p-3">種別更新</h1>
<div class="px-5">
    <form method="post" class="container">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group row">
            <label class="col-lg-2 col-form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
            <div class="col-lg-2">
                {{ field }}
            </div>
        </div>
        {% endfor %}
        <a type="button" class="btn btn-outline-dark" href="{% url 'manageType:list' %}"><i class="bi bi-arrow-left mr-1"
                                                                                        style="font-size:20px"></i>戻る</a>
        <button type="submit" class="btn btn-outline-success">
            <i class="bi bi-plus mr-1" style="font-size:20px"></i>更新
        </button>
    </form>
    <form method="post" action="{% url 'manageType:delete' type.id %}" class="container">
        {% csrf_token %}
        <div class="text-right" style="width:60%">
            <button type="submit" class="btn btn-danger">
                <i class="bi bi-x mr-1" style="font-size:20px"></i>削除
            </button>
        </div>
    </form>


</div>
{% endblock %}